"""init

Revision ID: 89174d8fa725
Revises: 861dd84c8e5d
Create Date: 2026-05-03 12:43:18.451101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89174d8fa725'
down_revision = '861dd84c8e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('auth_refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_tokens_user_revoked', 'auth_refresh_tokens', ['user_id', 'revoked'], unique=False)
    op.create_index(op.f('ix_auth_refresh_tokens_token_hash'), 'auth_refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_refresh_tokens_user_id'), 'auth_refresh_tokens', ['user_id'], unique=False)
    op.create_table('auth_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('privilege_level', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'ACTIVE', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'DISPUTED', name='contract_status'), server_default='PENDING_PAYMENT', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('client_id <> provider_id', name='ck_contract_client_provider_different'),
    sa.CheckConstraint('total_amount >= 0', name='ck_contract_total_amount_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contracts_status_created_at', 'contracts', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_contracts_client_id'), 'contracts', ['client_id'], unique=False)
    op.create_index(op.f('ix_contracts_listing_id'), 'contracts', ['listing_id'], unique=False)
    op.create_index(op.f('ix_contracts_provider_id'), 'contracts', ['provider_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'APPROVED', 'REJECTED', name='delivery_status'), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_milestone_id'), 'deliveries', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_deliveries_submitted_by'), 'deliveries', ['submitted_by'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('raised_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', name='dispute_status'), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_contract_id'), 'disputes', ['contract_id'], unique=False)
    op.create_index(op.f('ix_disputes_raised_by'), 'disputes', ['raised_by'], unique=False)
    op.create_table('escrow_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('escrow_account_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'RELEASE', 'REFUND', name='escrow_tx_type'), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escrow_transactions_escrow_account_id'), 'escrow_transactions', ['escrow_account_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id', 'action', 'key', name='uq_idem_actor_action_key')
    )
    op.create_index('idx_idem_expires_at', 'idempotency_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_actor_id'), 'idempotency_keys', ['actor_id'], unique=False)
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('marketplace_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_marketplace_categories_parent_id'), 'marketplace_categories', ['parent_id'], unique=False)
    op.create_table('marketplace_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='listing_status'), nullable=True),
    sa.Column('rating_avg', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_listings_category_id'), 'marketplace_listings', ['category_id'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_provider_id'), 'marketplace_listings', ['provider_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('reviewee_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reviews_comment_trgm', 'reviews', ['comment'], unique=False, postgresql_using='gin', postgresql_ops={'comment': 'gin_trgm_ops'})
    op.create_index('idx_reviews_search_vector', 'reviews', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_reviews_contract_id'), 'reviews', ['contract_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewee_id'), 'reviews', ['reviewee_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.create_table('user_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_credentials_user_id'), 'user_credentials', ['user_id'], unique=False)
    op.create_index('uq_user_credentials_email_lower', 'user_credentials', [sa.literal_column('lower(email)')], unique=True)
    op.create_index('uq_user_credentials_user_id', 'user_credentials', ['user_id'], unique=True)
    op.create_table('accounts_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('role_assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('contract_milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'FUNDED', 'DELIVERED', 'APPROVED', 'RELEASED', name='milestone_status'), server_default='PENDING', nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_milestone_amount_non_negative'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_milestones_contract_id'), 'contract_milestones', ['contract_id'], unique=False)
    op.create_table('escrow_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'LOCKED', 'CLOSED', name='escrow_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts_companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['accounts_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_companies_name_trgm', 'accounts_companies', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('idx_companies_search_vector', 'accounts_companies', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('accounts_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('town', sa.String(length=150), nullable=True),
    sa.Column('district', sa.String(length=150), nullable=True),
    sa.Column('region', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('profession_qualification', sa.String(length=255), nullable=True),
    sa.Column('academic_qualification', sa.String(length=255), nullable=True),
    sa.Column('is_offer_service', sa.Boolean(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('idx_profiles_academic_trgm', 'accounts_profiles', ['academic_qualification'], unique=False, postgresql_using='gin', postgresql_ops={'academic_qualification': 'gin_trgm_ops'})
    op.create_index('idx_profiles_full_name_trgm', 'accounts_profiles', ['full_name'], unique=False, postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.create_index('idx_profiles_profession_trgm', 'accounts_profiles', ['profession_qualification'], unique=False, postgresql_using='gin', postgresql_ops={'profession_qualification': 'gin_trgm_ops'})
    op.create_index('idx_profiles_search_vector', 'accounts_profiles', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('accounts_profile_languages',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'language_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts_profile_languages')
    op.drop_index('idx_profiles_search_vector', table_name='accounts_profiles', postgresql_using='gin')
    op.drop_index('idx_profiles_profession_trgm', table_name='accounts_profiles', postgresql_using='gin', postgresql_ops={'profession_qualification': 'gin_trgm_ops'})
    op.drop_index('idx_profiles_full_name_trgm', table_name='accounts_profiles', postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.drop_index('idx_profiles_academic_trgm', table_name='accounts_profiles', postgresql_using='gin', postgresql_ops={'academic_qualification': 'gin_trgm_ops'})
    op.drop_table('accounts_profiles')
    op.drop_index('idx_companies_search_vector', table_name='accounts_companies', postgresql_using='gin')
    op.drop_index('idx_companies_name_trgm', table_name='accounts_companies', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('accounts_companies')
    op.drop_table('escrow_accounts')
    op.drop_index(op.f('ix_contract_milestones_contract_id'), table_name='contract_milestones')
    op.drop_table('contract_milestones')
    op.drop_table('auth_role_permissions')
    op.drop_table('accounts_users')
    op.drop_index('uq_user_credentials_user_id', table_name='user_credentials')
    op.drop_index('uq_user_credentials_email_lower', table_name='user_credentials')
    op.drop_index(op.f('ix_user_credentials_user_id'), table_name='user_credentials')
    op.drop_table('user_credentials')
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewee_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_contract_id'), table_name='reviews')
    op.drop_index('idx_reviews_search_vector', table_name='reviews', postgresql_using='gin')
    op.drop_index('idx_reviews_comment_trgm', table_name='reviews', postgresql_using='gin', postgresql_ops={'comment': 'gin_trgm_ops'})
    op.drop_table('reviews')
    op.drop_index(op.f('ix_marketplace_listings_provider_id'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_category_id'), table_name='marketplace_listings')
    op.drop_table('marketplace_listings')
    op.drop_index(op.f('ix_marketplace_categories_parent_id'), table_name='marketplace_categories')
    op.drop_table('marketplace_categories')
    op.drop_table('languages')
    op.drop_index(op.f('ix_idempotency_keys_actor_id'), table_name='idempotency_keys')
    op.drop_index('idx_idem_expires_at', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_escrow_transactions_escrow_account_id'), table_name='escrow_transactions')
    op.drop_table('escrow_transactions')
    op.drop_index(op.f('ix_disputes_raised_by'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_contract_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_deliveries_submitted_by'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_milestone_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_contracts_provider_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_listing_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_client_id'), table_name='contracts')
    op.drop_index('idx_contracts_status_created_at', table_name='contracts')
    op.drop_table('contracts')
    op.drop_table('auth_roles')
    op.drop_index(op.f('ix_auth_refresh_tokens_user_id'), table_name='auth_refresh_tokens')
    op.drop_index(op.f('ix_auth_refresh_tokens_token_hash'), table_name='auth_refresh_tokens')
    op.drop_index('idx_refresh_tokens_user_revoked', table_name='auth_refresh_tokens')
    op.drop_table('auth_refresh_tokens')
    op.drop_table('auth_permissions')
    # ### end Alembic commands ###
